name: triton-embed_text-development-env
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python ==3.12.5
  - numpy ==1.26.4
  - protobuf
  - pytorch ==2.3.1
  - pytorch-cuda ==12.1
  - faiss-cpu
  - transformers ==4.42.4
  - accelerate ==0.32.1
  - sentencepiece ==0.2.0
  - scikit-learn
  - pillow
  - requests
  - ipython
  - ruff
  - isort
  - black
  - autoflake
  - pip
   #- pip:
     # pip deps
